# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'desafioS2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafioS2

  pod 'ReachabilitySwift', '~> 3'

  target 'desafioS2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafioS2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
